name = "Python"
language_id = "python"

[command]
default = ["python", "{file_path}"]
# On windows we have to use pythonw to prevent the console window from popping up.
Windows = ["pythonw", "{file_path}"]