name = "Python"
language_id = "python"
source_file_extension = "py"
compile = false

[command]
default = ["python", "{source_file_path}"]
# On windows we have to use pythonw to prevent the console window from popping up.
Windows = ["pythonw", "{source_file_path}"]